#!/system/bin/sh
#Governors
#Change CPU governor
#Ondemand*

echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 20000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo 0 > /sys/devices/system/cpu/cpufreq/ondemand/smooth_ui
