#!/sbin/busybox sh
#Semaphore Auto Brightness

if /sbin/busybox [ ! -f /system/.disable_autobr ]; then

echo 1 > /sys/devices/virtual/input/input7/enable

insmod /system/lib/modules/sema_autobr.ko

echo 35 > /sys/devices/virtual/misc/sema_autobr/min_brightness
echo 2700 > /sys/devices/virtual/misc/sema_autobr/max_lux
#echo 255 > /sys/devices/virtual/misc/sema_autobr/max_brightness
#echo 30 > /sys/devices/virtual/misc/sema_autobr/instant_update_thres
#echo 0 > /sys/devices/virtual/misc/sema_autobr/effect_delay_ms

fi
