#!/system/bin/sh
#Governors
#Change CPU governor
#SaveBattery

insmod /system/lib/modules/cpufreq_conservative.ko

echo conservative >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 10 >/sys/devices/system/cpu/cpufreq/conservative/freq_step
echo 75 >/sys/devices/system/cpu/cpufreq/conservative/down_threshold
echo 95 >/sys/devices/system/cpu/cpufreq/conservative/up_threshold
echo 0 >/sys/devices/system/cpu/cpufreq/conservative/ignore_nice_load
