#!/system/bin/sh
#Smooth UI
#Enable Smooth UI tunable on governors

echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/smooth_ui
echo 1 > /sys/devices/system/cpu/cpufreq/conservative/smooth_ui
echo 1 > /sys/devices/system/cpu/cpufreq/smartass/smooth_ui
