#!/system/bin/sh
#Netfilter
#Load netfilter modules (tethering, firewall)

insmod /system/lib/modules/nf_conntrack_ftp.ko
insmod /system/lib/modules/nf_conntrack_irc.ko
insmod /system/lib/modules/nf_conntrack_sip.ko
insmod /system/lib/modules/nf_nat.ko
insmod /system/lib/modules/nf_nat_ftp.ko
insmod /system/lib/modules/nf_nat_irc.ko
insmod /system/lib/modules/nf_nat_sip.ko

insmod /system/lib/modules/xt_policy.ko
insmod /system/lib/modules/xt_TCPMSS.ko
insmod /system/lib/modules/ipt_LOG.ko
insmod /system/lib/modules/ipt_REJECT.ko
insmod /system/lib/modules/iptable_nat.ko
insmod /system/lib/modules/ipt_MASQUERADE.ko
insmod /system/lib/modules/xt_state.ko
insmod /system/lib/modules/ipt_ULOG.ko

insmod /system/lib/modules/ipt_REDIRECT.ko
insmod /system/lib/modules/xt_multiport.ko
insmod /system/lib/modules/xt_connmark.ko
insmod /system/lib/modules/xt_NFLOG.ko


insmod /system/lib/modules/ip6t_LOG.ko
insmod /system/lib/modules/ip6t_REJECT.ko
