#!/system/bin/sh
#Netfilter
#Load netfilter modules (tethering, firewall)

insmod /system/lib/modules/nf_conntrack.ko
insmod /system/lib/modules/nf_conntrack_ftp.ko
insmod /system/lib/modules/nf_conntrack_irc.ko
insmod /system/lib/modules/nf_conntrack_sip.ko
insmod /system/lib/modules/nf_defrag_ipv4.ko
insmod /system/lib/modules/nf_conntrack_ipv4.ko
insmod /system/lib/modules/nf_nat.ko
insmod /system/lib/modules/nf_nat_ftp.ko
insmod /system/lib/modules/nf_nat_irc.ko
insmod /system/lib/modules/nf_nat_sip.ko
insmod /system/lib/modules/nfnetlink.ko
insmod /system/lib/modules/nfnetlink_log.ko
insmod /system/lib/modules/nf_conntrack_netlink.ko

insmod /system/lib/modules/x_tables.ko
insmod /system/lib/modules/xt_tcpudp.ko
insmod /system/lib/modules/xt_policy.ko
insmod /system/lib/modules/xt_mark.ko
insmod /system/lib/modules/xt_TCPMSS.ko
insmod /system/lib/modules/ip_tables.ko
insmod /system/lib/modules/ipt_LOG.ko
insmod /system/lib/modules/ipt_REJECT.ko
#insmod /system/lib/modules/ipt_ULOG.ko
insmod /system/lib/modules/iptable_filter.ko
insmod /system/lib/modules/iptable_mangle.ko
insmod /system/lib/modules/iptable_nat.ko
insmod /system/lib/modules/ipt_MASQUERADE.ko
insmod /system/lib/modules/xt_conntrack.ko
insmod /system/lib/modules/xt_state.ko
insmod /system/lib/modules/xt_NFLOG.ko

insmod /system/lib/modules/xt_owner.ko
insmod /system/lib/modules/ipt_REDIRECT.ko
insmod /system/lib/modules/xt_multiport.ko

insmod /system/lib/modules/ip6_tables.ko
insmod /system/lib/modules/ip6t_LOG.ko
insmod /system/lib/modules/ip6t_REJECT.ko
insmod /system/lib/modules/ip6t_ipv6header.ko
insmod /system/lib/modules/nf_conntrack_ipv6.ko

